services:
  db:
    image: postgres:15
    container_name: postgres_si1
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "9999:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/2_populate.sql

  # ----------------------------------------------------------------------------
  # Servicio: API de Gestión de Usuarios
  # ----------------------------------------------------------------------------
  user_api:
    build: .                      # Construir imagen desde Dockerfile en directorio actual
    ports:
      - "5050:5050"               # Mapear puerto 5050 del host al contenedor
    volumes:
      - ./:/app                   # Montar directorio actual en /app (desarrollo en tiempo real)
    command: python user.py       # Ejecutar servidor de usuarios al iniciar contenedor

  # ----------------------------------------------------------------------------
  # Servicio: API de Gestión de Archivos
  # ----------------------------------------------------------------------------
  api_api:
    build: .                      # Construir imagen desde Dockerfile en directorio actual
    ports:
      - "5051:5051"               # Mapear puerto 5051 del host al contenedor
    volumes:
      - ./:/app                   # Montar directorio actual en /app (desarrollo en tiempo real)
    command: python api.py       # Ejecutar servidor de archivos al iniciar contenedor