services:
  db:
    image: postgres:15
    container_name: postgres_si1
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "9999:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/2_populate.sql

  user_api:
    build: .
    container_name: user_si1
    command: python3 user.py
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: alumnodb
      DB_PASSWORD: 1234
      DB_NAME: si1
    volumes:
      - .:/app
    working_dir: /app
  
  api_api:
    build: .
    container_name: api_si1
    command: python3 api.py
    ports:
      - "5051:5051"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: alumnodb
      DB_PASSWORD: 1234
      DB_NAME: si1
    volumes:
      - .:/app
    working_dir: /app
